### ISSUE TITLE
Create a recipes

### ISSUE THREAD

**Issue by kells64000** [sensiolabs/StorybookBundle#22]
It would be cool to have a recipe in the [contrib repository](https://github.com/symfony/recipes-contrib).

This would allow you to manage the prerequisites at the installation stage instead of doing a `bin/console storybook:init`?

What do you think?

**Comment by jmwamser** [comment]
Would be happy to assist with the recipe. I noticed that this is currently in active development. Does it make sense to have `storybook:init` as a recipe at this point, or to wait just a little longer?

**Comment by squrious** [comment]
Hi! Yes a recipe would be a great improvement. The `storybook:init` command have some parts that could be extracted to a recipe, but the Storybook configuration files generation still requires a PHP script.

The recipe would contain:
- routes
- yaml config
- package.json (not sure about this one)
 
Then we'll still use the init command for preview template, `main.ts` and `preview.ts` generation and the example story (its location depends on the `main.ts` file).

WDYT?

**Comment by jmwamser** [comment]
I agree with the files you mentioned. I will have to think about the package.json file though.

Would there be a need to check if the user is using AssetMapper versus Encore versus just a package.json file?

**Comment by squrious** [comment]
> Would there be a need to check if the user is using AssetMapper versus Encore versus just a package.json file?

For the moment this bundle works only with AssetMapper. In order to make it work with Encore, we'll have to provide an alternative configuration/compilation mode to use Encore's webpack config in Storybook. But this is another story :smile:

**Comment by jmwamser** [comment]
> It would be cool to have a recipe in the [contrib repository](https://github.com/symfony/recipes-contrib).

@squrious, should this go in the "contrib" repository, or should it go in the ["official" repository](https://github.com/symfony/recipes)?

As I started to build it out I noticed we could do the following:

- routes
- yaml config
- stories directory template
- template bundle directory

Here is my initial thoughts on a [fork](https://github.com/jmwamser/recipes/commit/dcf5c591c9834c7d2b9e1269f75ee77000c5a4d9) of the "office" recipes lib.

**Comment by squrious** [comment]
Hi! 
> @squrious, should this go in the "contrib" repository, or should it go in the ["official" repository](https://github.com/symfony/recipes)?

This should go to the contrib repo :)

> Here is my initial thoughts on a [fork](https://github.com/jmwamser/recipes/commit/dcf5c591c9834c7d2b9e1269f75ee77000c5a4d9) of the "office" recipes lib.

Looks great to me, thanks for working on this! 

Just a few comments before we go to the PR:
- In the post install message, the first step looks not necessary to me, as you usually are in your project directory when you install dependencies
- The third step miss the "start Symfony server" part, but this may require additional checks on the generated configuration (port, https...). I would suggest to replace this with something like "follow the instructions provided by the storybook:init command" instead

**Comment by jmwamser** [comment]
Morning @squrious,

I have created symfony/recipes-contrib#1623 

It appears that the bundle's strict compatibility with Symfony 7 is causing some issues. Is there any particular reason we don't want this bundle to be available for Symfony 6.4 as well?

**Comment by squrious** [comment]
> It appears that the bundle's strict compatibility with Symfony 7 is causing some issues. Is there any particular reason we don't want this bundle to be available for Symfony 6.4 as well?

Hum no real reason, I think it's a misconfiguration in our `composer.json`. I just tested with 6.4 packages and it works fine :smile:

**Comment by jmwamser** [comment]
It looks like the PR for the recipe was merged in. @squrious or @kells64000 I believe this one can be marked as closed now :D

**Comment by squrious** [comment]
Yeah, thank you @jmwamser for your work on this!
