### ISSUE TITLE
v0.1.1 has not been published on packagist

### ISSUE THREAD

**Issue by bdecarne** [sensiolabs/StorybookBundle#25]
The v0.1.1 has not been published on packagist. 

It still installs 0.1.0 which is buggy

**Comment by mhlozek** [comment]
Same problem here.
I wanted to try storybookBundle with Symfony 6.4, but on packagist is v0.1.0 which require Symfony 7.

**Comment by squrious** [comment]
Hello there, indeed there was a problem here. I updated the package.
