### ISSUE TITLE
Args with null value fail in story

### ISSUE THREAD

**Issue by Fred-QS** [sensiolabs/StorybookBundle#39]
```js
import Message from "../../templates/components/Message.html.twig";

export default {
    component: Message,
    argTypes: {
        chat: {table: {disable: true}},
    },
    args: {
        chat: null
    }
}

export const Default = {};
```

![Capture d’écran du 2024-10-25 15-16-46](https://github.com/user-attachments/assets/9c39c5c7-28c0-43fd-b71e-103c592f3f06)

**Comment by squrious** [comment]
@Fred-QS Just checked the code, the issue was fixed when I refactored the actions addon integration, but it was not part of the 0.1.1 release.. If you use the latest version 0.1.2 that I just published, you should not encounter this issue anymore.
