### ISSUE TITLE
Error if /var/storybook is not create manually

### ISSUE THREAD

**Issue by WebMamba** [sensiolabs/StorybookBundle#6]
<e> [webpack-dev-middleware] [Error: ENOENT: no such file or directory, open '/Users/matheodaninos/Project/contributing/storybook_doc/var/storybook/preview.html'] {
<e>   errno: -2,
<e>   code: 'ENOENT',
<e>   syscall: 'open',
<e>   path: '/Users/matheodaninos/Project/contributing/storybook_doc/var/storybook/preview.html'
<e> }

We have the following error if the storybook directory is not create manually in the /var directory

**Comment by squrious** [comment]
We don't use the `var` directory anymore, so let's close this one :)
